<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /Users/USER/buildkit/build/mastercore/sites/default/files/civicrm/ext/uk.co.vedaconsulting.module.civicrmpostcodelookup/xml/schema/CRM/Civicrmpostcodelookup/PafPostcodeLookup.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:b28c2686aecf4b47c913339b39afd3ec)
 */

/**
 * Database access object for the PafPostcodeLookup entity.
 */
class CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'paf_post_code_lookup';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique PafPostcodeLookup ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * @var string
   */
  public $post_code;

  /**
   * @var string
   */
  public $post_town;

  /**
   * @var string
   */
  public $dependent_locality;

  /**
   * @var string
   */
  public $double_dependent_locality;

  /**
   * @var string
   */
  public $thoroughfare_descriptor;

  /**
   * @var string
   */
  public $dependent_thoroughfare_descriptor;

  /**
   * @var string
   */
  public $building_number;

  /**
   * @var string
   */
  public $building_name;

  /**
   * @var string
   */
  public $sub_building_name;

  /**
   * @var string
   */
  public $po_box;

  /**
   * @var string
   */
  public $department_name;

  /**
   * @var string
   */
  public $organisation_name;

  /**
   * @var string
   */
  public $udprn;

  /**
   * @var string
   */
  public $postcode_type;

  /**
   * @var string
   */
  public $su_organisation_indicator;

  /**
   * @var string
   */
  public $delivery_point_suffix;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'paf_post_code_lookup';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Unique PafPostcodeLookup ID'),
          'required' => TRUE,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'post_code' => [
          'name' => 'post_code',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Post Code'),
          'maxlength' => 12,
          'size' => CRM_Utils_Type::EIGHT,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'post_town' => [
          'name' => 'post_town',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Post Town'),
          'maxlength' => 30,
          'size' => CRM_Utils_Type::MEDIUM,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'dependent_locality' => [
          'name' => 'dependent_locality',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Dependent Locality'),
          'maxlength' => 35,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'double_dependent_locality' => [
          'name' => 'double_dependent_locality',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Double Dependent Locality'),
          'maxlength' => 35,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'thoroughfare_descriptor' => [
          'name' => 'thoroughfare_descriptor',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Thoroughfare Descriptor'),
          'maxlength' => 80,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'dependent_thoroughfare_descriptor' => [
          'name' => 'dependent_thoroughfare_descriptor',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Dependent Thoroughfare Descriptor'),
          'maxlength' => 80,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'building_number' => [
          'name' => 'building_number',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Building Number'),
          'maxlength' => 4,
          'size' => CRM_Utils_Type::FOUR,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'building_name' => [
          'name' => 'building_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Building Name'),
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'sub_building_name' => [
          'name' => 'sub_building_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Sub Building Name'),
          'maxlength' => 30,
          'size' => CRM_Utils_Type::MEDIUM,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'po_box' => [
          'name' => 'po_box',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('PO Box'),
          'maxlength' => 6,
          'size' => CRM_Utils_Type::SIX,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'department_name' => [
          'name' => 'department_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Department Name'),
          'maxlength' => 60,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'organisation_name' => [
          'name' => 'organisation_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Organisation Name'),
          'maxlength' => 60,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'udprn' => [
          'name' => 'udprn',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('UDPRN'),
          'maxlength' => 8,
          'size' => CRM_Utils_Type::EIGHT,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'postcode_type' => [
          'name' => 'postcode_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Postcode Type'),
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'su_organisation_indicator' => [
          'name' => 'su_organisation_indicator',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Organisation Indicator'),
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
        'delivery_point_suffix' => [
          'name' => 'delivery_point_suffix',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Civicrmpostcodelookup_ExtensionUtil::ts('Delivery Point Suffix'),
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'table_name' => 'paf_post_code_lookup',
          'entity' => 'PafPostcodeLookup',
          'bao' => 'CRM_Civicrmpostcodelookup_DAO_PafPostcodeLookup',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, '_code_lookup', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, '_code_lookup', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_post_code' => [
        'name' => 'index_post_code',
        'field' => [
          0 => 'post_code',
        ],
        'localizable' => FALSE,
        'sig' => 'paf_post_code_lookup::0::post_code',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
